// <auto-generated />
namespace Quizbee.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Surveyembeding : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Surveyembeding));
        
        string IMigrationMetadata.Id
        {
            get { return "201806220639488_Surveyembeding"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
