// <auto-generated />
namespace Quizbee.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _22june : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_22june));
        
        string IMigrationMetadata.Id
        {
            get { return "201806221522301_22june"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
